// Code generated by generator, DO NOT EDIT.
package test

import global "github.com/raito-io/object_diff_gen/global"

type AnotherTypeChangeSet struct {
	AnotherA *int
	AnotherB *string
}
type TestStructChangeSet struct {
	IntValue    *int
	StringValue *string
	TypeValue   *AnotherTypeChangeSet
	IntPtr      *int
	StringPtr   *string
	TypePtr     *AnotherTypeChangeSet
	ArrayInt    *global.ArrayDiff[int]
	ArrayObject *global.ArrayObjectDiff[AnotherType, AnotherTypeChangeSet]
}
